#!/bin/bash

# Copyright 2017 Midokura SARL

# The first existing directory is used for JAVA_HOME if needed.
LIB_PATTERNS='{lib64,lib}'
JVM_SEARCH_DIRS=$( eval echo \
                 /usr/$LIB_PATTERNS/jvm/java-1.8.0-openjdk-amd64 \
                 /usr/$LIB_PATTERNS/jvm/java-8-openjdk-amd64 \
                 /usr/$LIB_PATTERNS/jvm/java-8-oracle \
                 /usr/$LIB_PATTERNS/jvm/zulu-8-amd64 \
                 /usr/$LIB_PATTERNS/jvm/jre-1.8.0-openjdk \
                 /usr/$LIB_PATTERNS/jvm/jre-8-oracle-x64 \
                 /usr/$LIB_PATTERNS/jvm/jdk-8-oracle-x64)

# zulu prints "openjdk version" while openjdk and oracle print "java version"
check_for_java8() {
    [ "x" = "x$1" ] && return 1
    [ -x "$1" ] || return 1
    $1 -version 2>&1 | grep -q 'version "1.8'
}

if [ -n "`which java`" ]; then
        java=`which java`
        # Dereference symlink(s)
        while true; do
            if [ -h "$java" ]; then
                java=`readlink -f "$java"`
                continue
            fi
            break
        done
        CUR_JAVA_DIR=$(dirname $java | sed 's!\(/jre\)*/bin!!')
        JVM_SEARCH_DIRS="$CUR_JAVA_DIR $JVM_SEARCH_DIRS"
fi
if [ ! -z "$JAVA_HOME" ]; then
    JVM_SEARCH_DIRS="$JAVA_HOME $JVM_SEARCH_DIRS"
fi

oldopts=$-
set +e
JAVA_HOME=
for jdir in $JVM_SEARCH_DIRS; do
    check_for_java8 "$jdir/bin/java"
    if [ $? -eq 0 ]; then
        JAVA_HOME="$jdir"
        break
    fi
done
echo $oldopts | grep 'e' 2>&1 >/dev/null && set -e

if [ -z "$JAVA_HOME" ] ; then
    echo "No suitable JVM found (at least v1.8.0 required)"
    exit 1
fi

JAVA="$JAVA_HOME/bin/java"
